In [9]:
import numpy as np
import pandas as pd
import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as md
import matplotlib
import yfinance as yf

# Import Data

In [65]:
vol_data = pd.read_csv('~/Code/giadapi/crypto/raw_data/all_columns_daily_090323.csv',lineterminator='\n')
vol_data

,Unnamed: 0,date,negative_bert,neutral_bert,positive_bert,daily_tweets,MA7_Sentiment,MA20_Sentiment,MA50_Sentiment,BTC_price
0,0,2021-01-01,0.083330,0.493347,0.423323,12561.859509,NaN,NaN,NaN,29374.152344
1,1,2021-01-02,0.134531,0.438811,0.426658,30124.352145,NaN,NaN,NaN,32127.267578
2,2,2021-01-03,0.147802,0.428930,0.423267,26167.331282,NaN,NaN,NaN,32782.023438
3,3,2021-01-04,0.104159,0.507274,0.388567,18041.199084,NaN,NaN,NaN,31971.914062
4,4,2021-01-05,0.081743,0.521464,0.396793,17473.551568,NaN,NaN,NaN,33992.429688
...,...,...,...,...,...,...,...,...,...,...
793,793,2023-03-05,0.107813,0.541465,0.350722,14968.952910,0.358301,0.358391,0.363660,22435.513672
794,794,2023-03-06,0.109010,0.507571,0.383419,137824.833122,0.359351,0.359776,0.363419,22429.757812
795,795,2023-03-07,0.123972,0.520640,0.355388,19028.050010,0.360315,0.359762,0.363403,22219.769531
796,796,2023-03-08,0.087879,0.515427,0.396694,19216.616481,0.366446,0.360095,0.364243,21718.080078
797,797,2023-03-09,0.103576,0.593262,0.303163,11235.164835,0.359564,0.356971,0.363114,20363.021484

In [76]:
tweet_data = pd.read_csv('~/Code/giadapi/crypto/raw_data/cleaned_tweets_without_dupes_120323.csv',lineterminator='\n', index_col=0)
tweet_data

,datetime,username,text,date,negative_bert,neutral_bert,positive_bert
0,2021-01-01 22:09:59+00:00,sivilianlife,What's the chances @Grayscale is hedging short...,2021-01-01,0.002040,0.951312,0.046648
1,2021-01-01 22:09:39+00:00,LudicrousSpeed9,@CNBC Buy #Bitcoin to hedge against the result...,2021-01-01,0.004157,0.400750,0.595093
2,2021-01-01 22:09:35+00:00,SergioBowers1,@APompliano @pepsi @MonsterEnergy $DEO $KO e...,2021-01-01,0.000248,0.582107,0.417644
3,2021-01-01 22:09:21+00:00,bitvestor,Closed another chunk of this long now. Remaind...,2021-01-01,0.000974,0.807066,0.191960
4,2021-01-01 22:09:18+00:00,FROMKAIWITHLOVE,When you dig deeper into #kardiachain company ...,2021-01-01,0.000056,0.223449,0.776495
...,...,...,...,...,...,...,...
347663,2023-03-09 06:00:01+00:00,HourlyBTCUpdate,Bitcoin: $21739.58\nðŸ’” -1.72 last 1 Hour (-0.01...,2023-03-09,0.001016,0.870834,0.128149
347664,2023-03-09 06:00:01+00:00,Mannny23,Popular crypto latest prices:\n $BTC 21751.00\...,2023-03-09,0.003519,0.907121,0.089360
347665,2023-03-09 06:00:01+00:00,whalesradar_com,#CTXCUSDT #CTXC \nSignal #4 \n\nLast Signal: ...,2023-03-09,0.000521,0.964454,0.035024
347666,2023-03-09 06:00:00+00:00,croxroadnews,The Wings of #Bitcoin: A Symbol of Strength an...,2023-03-09,0.007388,0.532228,0.460384
347667,2023-03-09 06:00:00+00:00,AlphaImpact_fi,"#GM Alphas, itâ€™s time to announce a GOLDEN Rew...",2023-03-09,0.001678,0.591128,0.407194

In [88]:
file_name = f"{'2023-03-09'}_{'2023-03-14'}_twitter_cleaned.csv"
new_tweet_data = pd.read_csv(f"~/code/giadapi/crypto/{file_name}",lineterminator='\n', index_col=0)
new_tweet_data

,datetime,username,date,text,negative_bert,neutral_bert,positive_bert
0,2023-03-09 06:09:06+00:00,investor_shyla1,2023-03-09,I believe there is an 80% chance #BitcoinÂ hit...,0.034752,0.542985,0.422263
1,2023-03-09 06:08:45+00:00,AHzCrypto,2023-03-09,"I was Max bullish on #Bitcoin at the bottom, ...",0.005958,0.667002,0.327040
2,2023-03-09 06:08:33+00:00,weeblueghost,2023-03-09,"- BTC price: $21,722 / Â£18,151 46.03 Naks p...",0.012369,0.835802,0.151829
3,2023-03-09 06:08:27+00:00,Available4Sale,2023-03-09,ðŸ“¢ Premium domain name that can be used to off...,0.000358,0.714242,0.285400
4,2023-03-09 06:08:27+00:00,Bitcoin8News,2023-03-09,"The $BTC price is at $21,732.23 right now. ðŸ”´ C...",0.724548,0.190034,0.085419
...,...,...,...,...,...,...,...
2514,2023-03-14 22:00:33+00:00,ashleygrilo12,2023-03-14,They are about to turn the money printers on a...,0.000570,0.312646,0.686783
2515,2023-03-14 22:00:30+00:00,BtcPulse,2023-03-14,BTC hourly update $24658.30 | -0.54%ðŸ“‰ $B...,0.368925,0.523527,0.107548
2516,2023-03-14 22:00:29+00:00,Bcubeai,2023-03-14,#Bitcoin rallied 10% in one day. The next ones...,0.000383,0.454934,0.544683
2517,2023-03-14 22:00:29+00:00,EvertryLtd,2023-03-14,Bitcoin price alert 2023-03-14 22:00:28 GMT BT...,0.005007,0.315884,0.679109
2518,2023-03-14 22:00:25+00:00,JumpLineAlerts,2023-03-14,BTCUSDT [1h]: Open Interest Drop -3% $BTC #BT...,0.047071,0.627799,0.325131

In [ ]:
~/code/giadapi/crypto/{file_name}"

# Create vol_data

In [79]:
# Concern of order of data too


# Get daily tweets from tweet_data
def tweet_daily_rate(tweet_data_original):
    tweet_data = tweet_data_original.copy()
    
    tweet_data['datetime'] = pd.to_datetime(tweet_data['datetime'])
    tweet_data['hour'] = tweet_data['datetime'].dt.hour
    tweet_data['date'] = tweet_data['datetime'].dt.date
    
    daily_tweets = tweet_data.groupby(['date', 'hour']).agg({'negative_bert':'mean',
                                                 'neutral_bert':'mean',
                                                 'positive_bert':'mean',
                                                 'text':'count',
                                                 'datetime': lambda x: x.max() - x.min()})
    
    
    
    daily_tweets['datetime_seconds'] = daily_tweets['datetime'].dt.total_seconds()
    daily_tweets['tweets_rate'] = daily_tweets['text']/(daily_tweets['datetime_seconds'])
    daily_tweets_col = daily_tweets.groupby('date').agg({'tweets_rate':'mean'})
    daily_tweets_col['tweets_rate']*86400
    
    cut_off =daily_tweets.columns.get_loc("positive_bert")
    vol_data = daily_tweets.iloc[:,:cut_off+1]

    vol_data.reset_index(inplace=True)
    vol_data.drop('hour',axis=1,inplace=True)

    vol_data = vol_data.groupby(['date']).agg({'negative_bert':'mean',
                                        'neutral_bert':'mean',
                                        'positive_bert':'mean',
                                        })
    
    daily_tweets_col = daily_tweets.groupby('date').agg({'tweets_rate':'mean'})
    vol_data['daily_tweets'] = daily_tweets_col['tweets_rate']*86400
    vol_data.reset_index(inplace=True)
    return vol_data

# Pull btc price
def load_historic_data(symbol, start_date_str, end_date_str, period, interval):
    try:
        df = yf.download(symbol, start=start_date_str, end=end_date_str, period=period, interval=interval)
        #  Add symbol
    
        df["Symbol"] = symbol
        df['price_change'] = df['Close'].pct_change()
        return df
    except:
        print(f'Error loading stock data for + {symbol}')
        return None

# Convert tweet_data to vol_data (Adding moving averages,btc)
# Automate saving of the file?
def daily_data(tweet_data, filename, start_date_str=None,symbol='BTC-USD', end_date_str=None, period='1d', interval='1d'):
    
    vol_data = tweet_daily_rate(tweet_data)
    
    if start_date_str == None:
        v_date = vol_data.columns.get_loc("date")
        start_date_str = vol_data.iloc[-1,v_date]
    
    vol_data['MA7_Sentiment'] = vol_data['positive_bert'].rolling(window=8).mean()
    vol_data['MA20_Sentiment'] = vol_data['positive_bert'].rolling(window=21).mean()
    vol_data['MA50_Sentiment'] = vol_data['positive_bert'].rolling(window=51).mean()
    
    if end_date_str == None:
        today = datetime.date.today()
        today_str = datetime.datetime.strftime(today, "%Y-%m-%d")
        BTC_price = pd.DataFrame(load_historic_data(symbol, start_date_str, today_str, period, interval))
    else:
        BTC_price = pd.DataFrame(load_historic_data(symbol, start_date_str, end_date_str, period, interval))                    
    
    vol_data['BTC_price']=BTC_price.reset_index()['Adj Close']
    vol_data['BTC_trading_volume']=BTC_price.reset_index()['Volume']
    
    vol_data = vol_data[['date','negative_bert', 'neutral_bert', 'positive_bert',
       'daily_tweets', 'MA7_Sentiment', 'MA20_Sentiment',
       'MA50_Sentiment', 'BTC_price','BTC_trading_volume']]
    
    
    vol_data.to_csv(f'{fliename}.csv')
    return vol_data

In [82]:
daily_data(new_tweet_data, '09=',start_date_str='2023-03-09', symbol='BTC-USD', end_date_str=None, period='1d', interval='1d')

[*********************100%***********************]  1 of 1 completed

,date,negative_bert,neutral_bert,positive_bert,daily_tweets,MA7_Sentiment,MA20_Sentiment,MA50_Sentiment,BTC_price,BTC_trading_volume
0,2023-03-09,0.122177,0.534318,0.343505,19786.498716,NaN,NaN,NaN,20363.021484,30364664171
1,2023-03-10,0.121843,0.496890,0.381267,24014.458810,NaN,NaN,NaN,20187.244141,39578257695
2,2023-03-11,0.119182,0.482077,0.398741,21630.682739,NaN,NaN,NaN,20632.410156,30180288176
3,2023-03-12,0.141193,0.476507,0.382300,19517.885599,NaN,NaN,NaN,22163.949219,29279035521
4,2023-03-13,0.129297,0.493028,0.377675,25710.338003,NaN,NaN,NaN,24197.533203,49466362688
5,2023-03-14,0.101304,0.504696,0.394000,46629.599136,NaN,NaN,NaN,24746.074219,54622230164

In [67]:
tweet_daily_rate(tweet_data)

           date  negative_bert  neutral_bert  positive_bert   daily_tweets
0    2021-01-01       0.085275      0.489181       0.425545   12561.859509
1    2021-01-02       0.143365      0.439075       0.417560   30124.352145
2    2021-01-03       0.148220      0.432023       0.419757   26167.331282
3    2021-01-04       0.101558      0.507526       0.390916   18041.199084
4    2021-01-05       0.088530      0.517456       0.394014   17473.551568
..          ...            ...           ...            ...            ...
793  2023-03-05       0.105341      0.541416       0.353243   14968.952910
794  2023-03-06       0.112846      0.511105       0.376049  137824.833122
795  2023-03-07       0.123046      0.522288       0.354666   19028.050010
796  2023-03-08       0.088453      0.518017       0.393530   19216.616481
797  2023-03-09       0.103576      0.593262       0.303163   11235.164835

[798 rows x 5 columns]

In [75]:
vol_data.iloc[-1,:]

Unnamed: 0                 797
date                2023-03-09
negative_bert         0.103576
neutral_bert          0.593262
positive_bert         0.303163
daily_tweets      11235.164835
MA7_Sentiment         0.359564
MA20_Sentiment        0.356971
MA50_Sentiment        0.363114
BTC_price         20363.021484
Name: 797, dtype: object